import java.util.ArrayList;
import java.util.Arrays;

public class BoardInfo {
    byte[][] board;
    int[] passant;
    boolean[] hasMoved;
    ArrayList<Byte> deadPieces;
    String previousMove;

    byte whiteKingX;
    byte whiteKingY;

    byte blackKingX;
    byte blackKingY; 

    public BoardInfo(byte[][] board, int[] passant, boolean[] hasMoved, ArrayList<Byte> deadPieces){

        this.board = board;
        this.passant = passant;
        this.hasMoved = hasMoved;
        this.deadPieces = deadPieces;
    }
    
    
    
    /**
     * Method for evaluating the value of the board. Evaluating a board means to
     * apply a value for it,
     * this is used in the minimax algorithm.
     * 
     * @return an Integer represnting the score for this board.
     */
    public int evaluate() {
        return 0;
    }

    /**
     * Method for deep copying a BoardInfo object. 
     * @return A new BoardInfo object that is a deep copy of the original. 
     */
    public BoardInfo copy(){
        return new BoardInfo(deepCopy(board), Arrays.copyOf(passant, passant.length), Arrays.copyOf(hasMoved, hasMoved.length), new ArrayList<Byte>(deadPieces));
    }




    /**
     * Sets the previous move string. This string is used to determine which move led to a move to create the board.
     * If the string is null, that means that this board was not generated by the bot.
     * The pattern for the string goes first as a single character, numbers representing the id, followed by a period, then two digits
     * represnting the new location. 
     * 
     * @param move The new string to set it to.
     */
    public void setPreviousMove(String move){
        this.previousMove = move;

    }

    public byte[][] deepCopy(byte[][] original){
        byte[][] newArray = new byte[original.length][original[0].length];
        for(int i = 0; i < original.length; i++){
            newArray[i] = Arrays.copyOf(original[i], original[i].length);
        }
        return newArray;

    }

    public void setKingPos(boolean black, byte x, byte y){
        if(black){
            blackKingX = x;
            blackKingY = y;
        } else {
            whiteKingX = x;
            whiteKingY = y;
        }
    }
    
}
